### ISSUE TITLE
Failed to connect through remote host

### ISSUE THREAD

**Issue by pushkalkatara** [Dingry/BunnyVisionPro#7]
Hi, I'm trying to run on a local network connecting with a hotspot, but the server is unable to find the device. How do i debug this? What might be the issue?

The logs are as follows:
```
[INFO] [launch]: All log files can be found below /root/.ros/log/2024-08-22-00-23-41-285466-pushkal-591
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [bimanual_hand_detector_node.py-1]: process started with pid [592]
[bimanual_hand_detector_node.py-1] [INFO] [1724286221.424917811] [visionpro_hand_detector]: Beginning VisionPro hand detector node with name: visionpro. Waiting for initial data from 192.0.0.2.
[bimanual_hand_detector_node.py-1] Traceback (most recent call last):
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py", line 136, in stream
[bimanual_hand_detector_node.py-1]     for response in responses:
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 543, in __next__
[bimanual_hand_detector_node.py-1]     return self._next()
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/grpc/_channel.py", line 969, in _next
[bimanual_hand_detector_node.py-1]     raise self
[bimanual_hand_detector_node.py-1] grpc._channel._MultiThreadedRendezvous: <_MultiThreadedRendezvous of RPC that terminated with:
[bimanual_hand_detector_node.py-1] 	status = StatusCode.UNAVAILABLE
[bimanual_hand_detector_node.py-1] 	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:192.0.0.2:12345: Failed to connect to remote host: FD Shutdown"
[bimanual_hand_detector_node.py-1] 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:192.0.0.2:12345: Failed to connect to remote host: FD Shutdown", grpc_status:14, created_time:"2024-08-22T00:24:01.42642336+00:00"}"
[bimanual_hand_detector_node.py-1] >
[bimanual_hand_detector_node.py-1] 
[bimanual_hand_detector_node.py-1] During handling of the above exception, another exception occurred:
[bimanual_hand_detector_node.py-1] 
[bimanual_hand_detector_node.py-1] Traceback (most recent call last):
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py", line 323, in <module>
[bimanual_hand_detector_node.py-1]     main()
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py", line 314, in main
[bimanual_hand_detector_node.py-1]     hand_detector_node.start()
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py", line 122, in start
[bimanual_hand_detector_node.py-1]     self.stream()
[bimanual_hand_detector_node.py-1]   File "/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py", line 171, in stream
[bimanual_hand_detector_node.py-1]     self.get_logger().error(e)
[bimanual_hand_detector_node.py-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/impl/rcutils_logger.py", line 345, in error
[bimanual_hand_detector_node.py-1]     return self.log(message, LoggingSeverity.ERROR, **kwargs)
[bimanual_hand_detector_node.py-1]   File "/opt/ros/humble/local/lib/python3.10/dist-packages/rclpy/impl/rcutils_logger.py", line 318, in log
[bimanual_hand_detector_node.py-1]     _rclpy.rclpy_logging_rcutils_log(
[bimanual_hand_detector_node.py-1] TypeError: rclpy_logging_rcutils_log(): incompatible function arguments. The following argument types are supported:
[bimanual_hand_detector_node.py-1]     1. (arg0: int, arg1: str, arg2: str, arg3: str, arg4: str, arg5: int) -> None
[bimanual_hand_detector_node.py-1] 
[bimanual_hand_detector_node.py-1] Invoked with: <LoggingSeverity.ERROR: 40>, 'visionpro_hand_detector', <_MultiThreadedRendezvous of RPC that terminated with:
[bimanual_hand_detector_node.py-1] 	status = StatusCode.UNAVAILABLE
[bimanual_hand_detector_node.py-1] 	details = "failed to connect to all addresses; last error: UNKNOWN: ipv4:192.0.0.2:12345: Failed to connect to remote host: FD Shutdown"
[bimanual_hand_detector_node.py-1] 	debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"failed to connect to all addresses; last error: UNKNOWN: ipv4:192.0.0.2:12345: Failed to connect to remote host: FD Shutdown", grpc_status:14, created_time:"2024-08-22T00:24:01.42642336+00:00"}"
[bimanual_hand_detector_node.py-1] >, 'stream', '/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py', 171
[ERROR] [bimanual_hand_detector_node.py-1]: process has died [pid 592, exit code 1, cmd '/usr/local/lib/python3.10/dist-packages/bunny_teleop_server/nodes/bimanual_hand_detector_node.py --visionpro-name=visionpro --avp-ip=192.0.0.2 --ros-args'].
```

**Comment by pushkalkatara** [comment]
changing the network solved this issue!
